Repository alex-mottier/PRO-B01, pull requests merged in 2021-04, with the labels that each got.

#39 Fb b8 suivit qualite
  .github/workflows/CI_dev.yml
  .github/workflows/CI_fb.yml
  Client/src/__tests__/App.test.tsx
  Client/src/__tests__/__snapshots__/App.test.tsx.snap
Labels: quality

#42 Rebuild changes from FB-b7 to keep dev intact
  .env
  Client/Dockerfile
  Server/Dockerfile
  docker-compose.yml
Labels: infrastructure

#47 Fb c2 request2
  Server/Dockerfile
  Server/src/main/java/ch/amphytrion/project/controller/AddressController.java
  Server/src/main/java/ch/amphytrion/project/controller/ChatController.java
  Server/src/main/java/ch/amphytrion/project/controller/CityController.java
  Server/src/main/java/ch/amphytrion/project/controller/HostController.java
  Server/src/main/java/ch/amphytrion/project/controller/IGenericController.java
  Server/src/main/java/ch/amphytrion/project/controller/LocationController.java
  Server/src/main/java/ch/amphytrion/project/controller/MeetingController.java
  Server/src/main/java/ch/amphytrion/project/controller/MessageController.java
  Server/src/main/java/ch/amphytrion/project/controller/OpeningHourController.java
  Server/src/main/java/ch/amphytrion/project/controller/StudentController.java
  Server/src/main/java/ch/amphytrion/project/controller/TagController.java
  Server/src/main/java/ch/amphytrion/project/controller/UserController.java
  Server/src/main/java/ch/amphytrion/project/entities/Address.java
  Server/src/main/java/ch/amphytrion/project/entities/Chat.java
  Server/src/main/java/ch/amphytrion/project/entities/City.java
  Server/src/main/java/ch/amphytrion/project/entities/Host.java
  Server/src/main/java/ch/amphytrion/project/entities/Location.java
  Server/src/main/java/ch/amphytrion/project/entities/Meeting.java
  Server/src/main/java/ch/amphytrion/project/entities/Message.java
  Server/src/main/java/ch/amphytrion/project/entities/MessageImage.java
  Server/src/main/java/ch/amphytrion/project/entities/OpeningHour.java
  Server/src/main/java/ch/amphytrion/project/entities/Student.java
  Server/src/main/java/ch/amphytrion/project/entities/Tag.java
  Server/src/main/java/ch/amphytrion/project/entities/User.java
  Server/src/main/java/ch/amphytrion/project/repositories/AddressRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/ChatRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/CityRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/HostRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/LocationRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/MeetingRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/MessageImageRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/MessageRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/OpeningHourRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/StudentRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/TagRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/UserRepository.java
  Server/src/main/java/ch/amphytrion/project/services/AddressService.java
  Server/src/main/java/ch/amphytrion/project/services/ChatService.java
  Server/src/main/java/ch/amphytrion/project/services/CityService.java
  Server/src/main/java/ch/amphytrion/project/services/HostService.java
  Server/src/main/java/ch/amphytrion/project/services/IGenericService.java
  Server/src/main/java/ch/amphytrion/project/services/LocationService.java
  Server/src/main/java/ch/amphytrion/project/services/MeetingService.java
  Server/src/main/java/ch/amphytrion/project/services/MessageImageService.java
  Server/src/main/java/ch/amphytrion/project/services/MessageService.java
  Server/src/main/java/ch/amphytrion/project/services/OpeningHourService.java
  Server/src/main/java/ch/amphytrion/project/services/StudentService.java
  Server/src/main/java/ch/amphytrion/project/services/TagService.java
  Server/src/main/java/ch/amphytrion/project/services/UserService.java
  Server/src/main/resources/application-docker.properties
  Server/src/main/resources/application.properties
  Server/src/test/java/ch/amphytrion/project/repositories/ChatRepositoryTest.java
  Server/src/test/java/ch/amphytrion/project/repositories/MeetingRepositoryTest.java
  Server/src/test/java/ch/amphytrion/project/repositories/StudentRepositoryTest.java
Labels: backend, database
