Repository alex-mottier/PRO-B01, pull requests merged in 2021-05, with the labels that each got.

#60 Update Files for Heroku Prod
  .github/workflows/heroku.yml
  Server/src/main/resources/application.properties
Labels: infrastructure

#62 Deploy on push only
  .github/workflows/heroku.yml
Labels: infrastructure

#64 Fb d1
  Server/src/main/java/ch/amphytrion/project/authentication/SecurityConstants.java
  Server/src/main/java/ch/amphytrion/project/authentication/WebSecurity.java
  Server/src/main/java/ch/amphytrion/project/authentication/google_authentication/GoogleAuthenticationFilter.java
  Server/src/main/java/ch/amphytrion/project/controller/HostController.java
  Server/src/main/java/ch/amphytrion/project/controller/UserController.java
  Server/src/main/java/ch/amphytrion/project/dto/HostRequest.java
  Server/src/main/java/ch/amphytrion/project/dto/HostResponse.java
  Server/src/main/java/ch/amphytrion/project/dto/StudentRequest.java
  Server/src/main/java/ch/amphytrion/project/dto/UserResponse.java
  Server/src/main/java/ch/amphytrion/project/services/UserService.java
Labels: backend

#61 Fb nettoyage
  Server/src/main/java/ch/amphytrion/project/controller/AddressController.java
  Server/src/main/java/ch/amphytrion/project/controller/ChatController.java
  Server/src/main/java/ch/amphytrion/project/controller/CityController.java
  Server/src/main/java/ch/amphytrion/project/controller/MessageController.java
  Server/src/main/java/ch/amphytrion/project/controller/OpeningHourController.java
  Server/src/main/java/ch/amphytrion/project/controller/TagController.java
  Server/src/main/java/ch/amphytrion/project/dto/AuthenticateRequest.java
  Server/src/main/java/ch/amphytrion/project/dto/ConnectedUser.java
  Server/src/main/java/ch/amphytrion/project/dto/MessageResponse.java
  Server/src/main/java/ch/amphytrion/project/dto/SuccessResponse.java
  Server/src/main/java/ch/amphytrion/project/repositories/MeetingRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/MessageImageRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/MessageRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/OpeningHourRepository.java
  Server/src/main/java/ch/amphytrion/project/repositories/TagRepository.java
  Server/src/main/java/ch/amphytrion/project/services/AddressService.java
  Server/src/main/java/ch/amphytrion/project/services/CityService.java
  Server/src/main/java/ch/amphytrion/project/services/MessageImageService.java
  Server/src/main/java/ch/amphytrion/project/services/MessageService.java
  Server/src/main/java/ch/amphytrion/project/services/OpeningHourService.java
  Server/src/main/java/ch/amphytrion/project/services/TagService.java
  Server/src/test/java/ch/amphytrion/project/controller/AddressControllerTest.java
  Server/src/test/java/ch/amphytrion/project/controller/CityControllerTest.java
  Server/src/test/java/ch/amphytrion/project/controller/MessageResponseControllerTest.java
  Server/src/test/java/ch/amphytrion/project/controller/OpeningHourResponseControllerTest.java
  Server/src/test/java/ch/amphytrion/project/controller/TagResponseControllerTest.java
Labels: backend, quality

#69 Fb d2
  .github/workflows/heroku.yml
  Server/src/main/java/ch/amphytrion/project/controller/HostController.java
  Server/src/main/java/ch/amphytrion/project/controller/LocationController.java
  Server/src/main/java/ch/amphytrion/project/controller/UserController.java
  Server/src/main/java/ch/amphytrion/project/data/DataCreator.java
  Server/src/main/java/ch/amphytrion/project/dto/CovidDataResponse.java
  Server/src/main/java/ch/amphytrion/project/dto/HostRequest.java
  Server/src/main/java/ch/amphytrion/project/dto/HostResponse.java
  Server/src/main/java/ch/amphytrion/project/dto/SignUpHostRequest.java
  Server/src/main/java/ch/amphytrion/project/entities/databaseentities/CovidData.java
  Server/src/main/java/ch/amphytrion/project/entities/databaseentities/HostProfil.java
  Server/src/main/java/ch/amphytrion/project/entities/databaseentities/Location.java
  Server/src/main/java/ch/amphytrion/project/entities/databaseentities/OpeningHour.java
  Server/src/main/java/ch/amphytrion/project/repositories/MeetingRepository.java
  Server/src/main/java/ch/amphytrion/project/services/MeetingService.java
  Server/src/main/java/ch/amphytrion/project/services/UserService.java
Labels: backend

#72 Rename heroku.yml to heroku_master.yml
  .github/workflows/heroku_master.yml
Labels: infrastructure, quality

#76 fixed error 500 if login failed
  Server/src/main/java/ch/amphytrion/project/controller/IGenericController.java
Labels: bug

#77 Fb prepare for pr
  .github/workflows/heroku_master.yml
  Client/TODO.txt
  Client/app.json
  Client/src/app/authentication/GoogleAuth.ts
  Client/src/app/context/Globals.ts
  Client/src/app/context/Strings.ts
  Client/src/app/stores/AuthenticationStore.ts
  Client/src/app/stores/StudentStore.ts
  Client/src/screens/NoProfile/SignIn/SignIn.tsx
  Server/src/main/resources/application.properties
Labels: infrastructure, quality

#95 Fb front host
  Client/src/app/context/Globals.ts
  Client/src/app/context/Strings.ts
  Client/src/components/Location/LocationComponent.tsx
  Client/src/components/Meeting/MeetingComponent.tsx
  Client/src/components/Tags/TagsComponent.tsx
  Client/src/navigation/BottomHostTabs.tsx
  Client/src/navigation/BottomStudentTabs.tsx
  Client/src/navigation/StudentStack.tsx
Labels: frontend

#109 POST location is back
  Server/src/main/java/ch/amphytrion/project/controller/LocationController.java
Labels: backend, bug

#104 Fb fix issues
  Server/src/main/java/ch/amphytrion/project/controller/LocationController.java
  Server/src/main/java/ch/amphytrion/project/controller/MeetingController.java
  Server/src/main/java/ch/amphytrion/project/entities/databaseentities/Meeting.java
  Server/src/main/resources/application.properties
Labels: backend

#114 Fb patch dev
  Client/src/app/context/Globals.ts
  Server/src/main/resources/application.properties
Labels: backend

#116 Re-use dev values
  Client/src/app/context/Globals.ts
  Server/src/main/resources/application.properties
Labels: frontend
